dofbot_arm:
  ## joint_state_controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      - arm_joint_04
      - arm_joint_05
    sim_control_mode: 0 # 0: position, 1: velocity   
  ## joint effort controller  
  arm_joint_01_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint_01
    pid: {p: 100.0, i: 1.0, d: 1.0}  
  arm_joint_02_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint_02
    pid: {p: 100.0, i: 1.0, d: 1.0}  
  arm_joint_03_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_joint_03  
    pid: {p: 100.0, i: 1.0, d: 1.0}  
  arm_joint_04_position_controller:
    type: effort_controllersJointPositionController
    joint: arm_joint_04  
    pid: {p: 100.0, i: 1.0, d: 1.0}  
  arm_joint_05_position_controller:
    type: effort_controllersJointPositionController
    joint: arm_joint_05
    pid: {p: 100.0, i: 1.0, d: 1.0}  
