joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50 # Hertz

joint1_position_controller: 
  type: effort_controllers/JointPositionController  
  joint: arm_joint_01
  pid: 
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint2_position_controller: 
  type: effort_controllers/JointPositionController  
  joint: arm_joint_02
  pid:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint3_position_controller: 
  type: effort_controllers/JointPositionController  
  joint: arm_joint_03
  pid:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint4_position_controller: 
  type: effort_controllers/JointPositionController  
  joint: arm_joint_04
  pid:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint5_position_controller: 
  type: effort_controllers/JointPositionController  
  joint: arm_joint_05
  pid:
      p: 100
      d: 1
      i: 1
      i_clamp: 1